#ifndef __NANORPC_IFACE__
#define __NANORPC_IFACE__
/* 
   This file is automatically generated. Do not modify it directly, 
   instead modifiy the 'Wezel_1.xml' file and re-run RPCCodeGen tool again!

   This file is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.
  
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
  
   You should have received a copy of the GNU General Public License
   along with this program. If not, see http://www.gnu.org/licenses.
   
   The methodology, constrcutions and some use cases of this tool and 
   NanoRPC protocol was presented in: A.Pruszkowski, "Maszynowa 
   generacja oprogramowania dla dwumikrokontrolerowych wezlow Internetu 
   Rzeczy", in procidings PRZEGLAD TELEKOMUNIKACYJNY, 2015/8-9, 
   ISSN 1230-3496, e-ISSN 2449-7487, Pages: 861-868, 
   DOI:10.15199/59.2015.8-9.26
   
   Remarks: The memory replication mechanism was addad in July 2016. 
   This mechanism utilise the proxy protocol used in the SmartCampus 
   experiment. The experiment was desribed in: T.Tajmajer at al, 
   "Node/Proxy portability: Designing for the two lives of your next 
   WSAN middleware", Publicated in: Journal of Systems and Software, 
   Volume 117, July 2016, Pages 366-383, Elsevier, 
   https://doi.org/10.1016/j.jss.2016.03.035

   The below part of this file was created for 
   user: mjamroz at 2017-10-23 12:25:22 by RPCCodeGen.
   The RPCCodeGen tool was made by Aleksander Pruszkowski (apruszko@o2.pl)

   Developing history:
   2016.07.21 - Improved memory replication mechanism (the memory contents 
                migration is possible in the two directions).
   2016.04.29 - A few minor improvements (major cleaning of the python code).
   2016.07.01 - Added memory replication mechanism (the memory contenst 
                migration is realised from master part to slave part only).
   2015.09.20 - A few minor improvements (preprocessing source code).
   2015.04.08 - First working version, support only simple types of 
                arguments provided to services during invocation.
*/

//Communication support in external functions:
//void sendPoUART(uint8_t channel, uint8_t payload_len, uint8_t *payload);

//Error support in external functions:
void NANORPC_FRAME_ERROR(uint8_t error_val);

//Big-little endiannes in support external functions:
uint32_t MHTONL(uint32_t);
uint32_t MNTOHL(uint32_t);
uint16_t MHTONS(uint16_t);
uint16_t MNTOHS(uint16_t);

#endif //__NANORPC_IFACE__


